### ISSUE TITLE
Add Python3 to Pandoc container

### ISSUE THREAD

**Issue by aaron-gu** [nsheff/docker#2]
My Python user space is configured weirdly for Python2 and pip2 (something about must having to use `pip install` with the `--user` flag), and I can't get the Python2 in the container to use the pandocfilter library installed on my local computer. Adding Python3 to the container might allow the pip3 installed library to work with the container.

**Comment by nsheff** [comment]
Ok, I added pandocfilter to the pandoc container... can you try again with the new nsheff/pandoc container?

you will also need to update mediabuilder, since I updated pandoc while I was at it, and I had to update the templates for the new pandoc.

**Comment by aaron-gu** [comment]
The issue with the library import is gone now, but I am running into a Makefile issue:

```
~/Documents/UVA/databio//mediabuilder/bin/passthru `~/Documents/UVA/databio//mediabuilder/bin/ver src/*manuscript` | \
        pandoc \
        -o output/manuscript.pdf --filter ~/Documents/UVA/databio//mediabuilder/pandoc-wrapfig/pandoc-wrapfig.py --template ~/Documents/UVA/databio//mediabuilder/tex_templates/twocol.tex --bibliography  -
-csl ~/Documents/UVA/databio//mediabuilder/csl/nature.csl
[WARNING] Could not deduce format from file extension .csl
  Defaulting to markdown
Could not find bibliography file: --csl
Error running filter pandoc-citeproc:
Filter returned error status 1
make: *** [manuscript] Error 83
```

The flags are from an environment variable called $PANDOC_FLAGS, which I do not know where it's coming from.

**Comment by nsheff** [comment]
https://github.com/nsheff/mediabuilder/blob/a93e5ee89f4d5ce8ce695b99a820a8fc81abd554/mediabuilder.make#L22-L27

but anyway, that's not the problem -- you have not indicated a bibliography (the arg is empty), so it's passing the next arg, "--csl" as your bibliography. 

looks like it requires the bibliography for this. so, just set BIBTEXDB as instructed in the mediabuilder readme: 

export BIBTEXDB=path/to/db.bib

**Comment by aaron-gu** [comment]
I'm seeing some references in the paper that we haven't discussed before (Nagraj2018, Simovski2018, Dozmorov2016, Kanduri2019, Layer2018). Could you send me a copy of your bibliography?

**Comment by aaron-gu** [comment]
Nevermind, I can see the titles in your output pdf. `make manuscript` is working now!

**Comment by nsheff** [comment]
great. you can use 'make bibsub' to extract the refs for this paper from your primary bibtex database.
I've done that now and it extracted these refs here: 

output/refs.bib
